# Generated by Django 2.2.24 on 2022-02-05 10:44

from django.db import migrations


def fill_new_building_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    new_building_threshold_year = 2015
    for flat in Flat.objects.all():
        flat.new_building = flat.construction_year >= new_building_threshold_year
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building_field),
    ]
