# Generated by Django 2.2.24 on 2022-02-06 01:52

from django.db import migrations
import phonenumbers


def fill_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        corrected_phone_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(corrected_phone_number):
            flat.owner_pure_phone = corrected_phone_number
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(fill_phone_numbers),
    ]
