# Generated by Django 2.2.24 on 2022-02-06 14:25

from django.db import migrations


def transfer_owners_from_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            name=flat.owner,
            owner_pure_phone=flat.owner_pure_phone,
            owners_phonenumber=flat.owners_phonenumber
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20220206_1724'),
    ]

    operations = [
        migrations.RunPython(transfer_owners_from_flats_to_owners)
    ]
