# Generated by Django 2.2.24 on 2022-02-07 15:49

from django.db import migrations


def link_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for index, owner in enumerate(Owner.objects.all()):
        flats = Flat.objects.filter(owner=owner.name)
        owner.flats.set(flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20220207_1849'),
    ]

    operations = [
        migrations.RunPython(link_flats_to_owners, migrations.RunPython.noop),
    ]
